export const bancoPreguntas = [
    { q: "¿En qué ciudad-estado griega nació el concepto de 'Democracia'?", a: ["Esparta", "Atenas", "Tebas"], correcta: 1 },
    { q: "¿Cómo se llamaba la formación militar básica de los ciudadanos griegos?", a: ["Legión", "Falange", "Manípulo"], correcta: 1 },
    { q: "¿Quién fue el principal estratega de Atenas durante su 'Siglo de Oro'?", a: ["Pericles", "Leónidas", "Alejandro Magno"], correcta: 0 },
    { q: "¿Qué guerra enfrentó a Atenas contra Esparta por la hegemonía?", a: ["Guerras Médicas", "Guerra de Troya", "Guerra del Peloponeso"], correcta: 2 },
    { q: "¿Cómo llamaban los griegos a sus ciudades-estado independientes?", a: ["Polis", "Civitas", "Urbs"], correcta: 0 },
    { q: "¿Cuál era la clase social privilegiada en los inicios de la República Romana?", a: ["Plebeyos", "Patricios", "Libertos"], correcta: 1 },
    { q: "¿Contra qué potencia se enfrentó Roma en las Guerras Púnicas?", a: ["Egipto", "Macedonia", "Cartago"], correcta: 2 },
    { q: "¿Quién cruzó los Alpes con elefantes para atacar a Roma?", a: ["Julio César", "Aníbal Barca", "Escipión"], correcta: 1 },
    { q: "¿Cómo se llamó el periodo de paz iniciado por el emperador Augusto?", a: ["Pax Romana", "Pax Augusta", "Edad de Oro"], correcta: 0 },
    { q: "¿Qué institución era el centro del poder político en la República Romana?", a: ["El Consulado", "El Senado", "La Asamblea"], correcta: 1 },
    { q: "¿Qué filósofo griego fue el maestro de Alejandro Magno?", a: ["Platón", "Sócrates", "Aristóteles"], correcta: 2 },
    { q: "¿En qué año se sitúa la caída del Imperio Romano de Occidente?", a: ["476 d.C.", "1453 d.C.", "44 a.C."], correcta: 0 },
    { q: "¿Cómo se llamó el gobierno formado por César, Pompeyo y Craso?", a: ["Triunvirato", "Diarquía", "Tetrarquía"], correcta: 0 },
    { q: "¿Qué emperador romano legalizó el cristianismo (Edicto de Milán)?", a: ["Nerón", "Trajano", "Constantino"], correcta: 2 },
    { q: "¿Cuál era el nombre de la plaza pública en el centro de Roma?", a: ["Ágora", "Foro", "Panteón"], correcta: 1 },
    { q: "¿Qué orden arquitectónico griego tiene volutas en el capitel?", a: ["Dórico", "Jónico", "Corintio"], correcta: 1 },
    { q: "¿Cómo llamaban los romanos al Mar Mediterráneo?", a: ["Mare Magnum", "Mare Nostrum", "Oceanus"], correcta: 1 },
    { q: "¿Qué famoso esclavo lideró una rebelión de gladiadores?", a: ["Espartaco", "Crixo", "Máximo"], correcta: 0 },
    { q: "¿Qué sistema de gobierno de 4 líderes estableció Diocleciano?", a: ["Monarquía", "Tetrarquía", "Principado"], correcta: 1 },
    { q: "¿Quién fue el primer emperador de Roma?", a: ["Julio César", "Marco Aurelio", "César Augusto"], correcta: 2 }
];